### ISSUE TITLE
CI failure

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#1119]
https://travis-ci.com/sql-machine-learning/sqlflow/builds/134646446

```
=== RUN   TestCreateTrainAndValDataset
time="2019-11-02T02:06:38Z" level=error msg="create table failed: Error from server: TStatus({StatusCode:ERROR_STATUS InfoMessages:[*org.apache.hive.service.cli.HiveSQLException:Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask:17:16 org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380 org.apache.hive.service.cli.operation.SQLOperation:runQuery:SQLOperation.java:257 org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:293 org.apache.hive.service.cli.operation.Operation:run:Operation.java:320 org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530 org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506 org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280 org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531 org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437 org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422 org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39 org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39 org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56 org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286 java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1149 java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:624 java.lang.Thread:run:Thread.java:748] SqlState:0xc0003721b0 ErrorCode:0xc00034f8c0 ErrorMessage:0xc0003721c0}), sql: CREATE TABLE sqlflow_tv_orig AS SELECT *, RAND(42) AS sqlflow_rdm FROM (\nSELECT a.sepal_length,b.sepal_width,a.petal_length,b.petal_width,a.class\nFROM iris.train a,iris.test b\nWHERE a.class=b.class\nLIMIT 7\n) AS sqlflow_tv_orig_ori" package=sql
time="2019-11-02T02:06:38Z" level=error msg="create table with a random column failed, err: Error from server: TStatus({StatusCode:ERROR_STATUS InfoMessages:[*org.apache.hive.service.cli.HiveSQLException:Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask:17:16 org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380 org.apache.hive.service.cli.operation.SQLOperation:runQuery:SQLOperation.java:257 org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:293 org.apache.hive.service.cli.operation.Operation:run:Operation.java:320 org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530 org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506 org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280 org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531 org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437 org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422 org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39 org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39 org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56 org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286 java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1149 java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:624 java.lang.Thread:run:Thread.java:748] SqlState:0xc0003721b0 ErrorCode:0xc00034f8c0 ErrorMessage:0xc0003721c0})" package=sql
--- FAIL: TestCreateTrainAndValDataset (8.15s)
    create_train_val_test.go:55: 
        	Error Trace:	create_train_val_test.go:55
        	Error:      	Received unexpected error:
        	            	Error from server: TStatus({StatusCode:ERROR_STATUS InfoMessages:[*org.apache.hive.service.cli.HiveSQLException:Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask:17:16 org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380 org.apache.hive.service.cli.operation.SQLOperation:runQuery:SQLOperation.java:257 org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:293 org.apache.hive.service.cli.operation.Operation:run:Operation.java:320 org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530 org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506 org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280 org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531 org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437 org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422 org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39 org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39 org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56 org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286 java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1149 java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:624 java.lang.Thread:run:Thread.java:748] SqlState:0xc0003721b0 ErrorCode:0xc00034f8c0 ErrorMessage:0xc0003721c0})
        	Test:       	TestCreateTrainAndValDataset
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9e4917]
goroutine 10 [running]:
testing.tRunner.func1(0xc00026cc00)
	/usr/local/go/src/testing/testing.go:792 +0x387
panic(0xb4cd00, 0x13400a0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
sqlflow.org/sqlflow/pkg/sql.TestCreateTrainAndValDataset(0xc00026cc00)
	/go/src/sqlflow.org/sqlflow/pkg/sql/create_train_val_test.go:56 +0x1d7
testing.tRunner(0xc00026cc00, 0xc4adc8)
	/usr/local/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x35c
FAIL	sqlflow.org/sqlflow/pkg/sql	15.712s
?   	sqlflow.org/sqlflow/pkg/sql/codegen	[no test files]
```

**Comment by typhoonzero** [comment]
I encountered this error too and seems it appears randomly, will look into it.

**Comment by tonyyang-svail** [comment]
Looks like this issue has been fixed by https://github.com/sql-machine-learning/sqlflow/pull/1121.
