### ISSUE TITLE
SQLFlow can't run a BoostedTreesRegressor

### ISSUE THREAD

**Issue by shendiaomo** [sql-machine-learning/sqlflow#1546]
SQLFlow supports xgboost like demonstrated in [xgboost tutorial](https://sql-machine-learning.github.io/sqlflow/doc/tutorial/housing-xgboost/). The following training statements works well.
```sql
SELECT * FROM boston.train
TO TRAIN xgboost.gbtree
WITH
    objective="reg:squarederror",
    train.num_boost_round = 30
COLUMN crim, zn, indus, chas, nox, rm, age, dis, rad, tax, ptratio, b, lstat
LABEL medv
INTO sqlflow_models.my_xgb_regression_model;
```
[BoostedTreesRegressor](https://www.tensorflow.org/api_docs/python/tf/estimator/BoostedTreesClassifier?version=stable) is the TensorFlow implementation of GBDT as a canned estimator. SQLFlow should support all canned estimators. 
However, if we change the `xgboost.gbtree` in the above statement  to `BoostedTreesRegressor` like:

```sql
SELECT * FROM boston.train
TO TRAIN BoostedTreesRegressor
WITH model.n_batches_per_layer=300
COLUMN crim, zn, indus, chas, nox, rm, age, dis, rad, tax, ptratio, b, lstat
LABEL medv
INTO sqlflow_models.my_xgb_regression_model;
```

The following error will occur:
![image](https://user-images.githubusercontent.com/4180295/71460895-ac031300-27e8-11ea-9f2f-8d48bb37c007.png)

I believe this is a bug in shapes of features because `BoostedTreesEstimator` has to infer shapes from inputs, but SQLFlow didn't set shapes in the dataset.
https://github.com/sql-machine-learning/sqlflow/blob/f10c001a49e8657932c350d5460cb1e8f3b060e2/python/sqlflow_submitter/tensorflow/input_fn.py#L49
As we've seen, the above code doesn't provide the `shape` argument to `from_generator`, the shapes of input features are all `<unknown>`, that's the reason for the error 
```
ValueError: Cannot infer num from shape <unknown>

```

**Comment by shendiaomo** [comment]
The original error message looks like:
```python
Traceback (most recent call last):
  File "<stdin>", line 202, in <module>
  File "/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/train.py", line 228, in train
    metric_names)
  File "/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/train.py", line 152, in estimator_train_and_save
    result = tf.estimator.train_and_evaluate(classifier, train_spec, eval_spec)
  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 473, in train_and_evaluate
    return executor.run()
  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 613, in run
    return self.run_local()
  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 714, in run_local
    saving_listeners=saving_listeners)
  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 367, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1158, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1188, in _train_model_default
    features, labels, ModeKeys.TRAIN, self.config)
  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1146, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/canned/boosted_trees.py", line 1943, in _model_fn
    train_in_memory=train_in_memory)
  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/canned/boosted_trees.py", line 1088, in _bt_model_fn
    features, sorted_feature_columns, bucket_boundaries_dict)
  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/canned/boosted_trees.py", line 104, in _get_transformed_features
    bucket_boundaries_dict)
  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/canned/boosted_trees.py", line 173, in _get_transformed_features_and_merge_with_previously_transformed
    unstacked = array_ops.unstack(tensor, axis=1)
  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1186, in unstack
    raise ValueError("Cannot infer num from shape %s" % value_shape)
ValueError: Cannot infer num from shape <unknown>
```
