### ISSUE TITLE
Current MaxCompute parser (calcite) do not support where class!=2

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#1640]
Adding case `select * from my_table where class!=2` will cause the test `TestExternalParserCommonCasesForMaxCompute` fail, yet use `where class<>2` can pass.

```
=== RUN   TestExternalParserCommonCasesForMaxCompute
--- FAIL: TestExternalParserCommonCasesForMaxCompute (4.21s)
    parser_test.go:27:
        	Error Trace:	parser_test.go:27
        	            				java_parser_test.go:31
        	Error:      	Received unexpected error:
        	            	ERROR StatusLogger Unrecognized format specifier [d]
        	            	ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
        	            	ERROR StatusLogger Unrecognized format specifier [thread]
        	            	ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
        	            	ERROR StatusLogger Unrecognized format specifier [level]
        	            	ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
        	            	ERROR StatusLogger Unrecognized format specifier [logger]
        	            	ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
        	            	ERROR StatusLogger Unrecognized format specifier [msg]
        	            	ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
        	            	ERROR StatusLogger Unrecognized format specifier [n]
        	            	ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
        	            	ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
        	            	ERROR StatusLogger Unrecognized format specifier [d]
        	            	ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
        	            	ERROR StatusLogger Unrecognized format specifier [thread]
        	            	ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
        	            	ERROR StatusLogger Unrecognized format specifier [level]
        	            	ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
        	            	ERROR StatusLogger Unrecognized format specifier [logger]
        	            	ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
        	            	ERROR StatusLogger Unrecognized format specifier [msg]
        	            	ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
        	            	ERROR StatusLogger Unrecognized format specifier [n]
        	            	ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
        	            	Exception in thread "main" java.lang.NullPointerException
        	            		at org.sqlflow.parser.CalciteParserAdaptor.ParseAndSplit(CalciteParserAdaptor.java:40)
        	            		at org.sqlflow.parser.ParserAdaptorCmd.main(ParserAdaptorCmd.java:51)
        	            	 exit status 1
        	Test:       	TestExternalParserCommonCasesForMaxCompute
    parser_test.go:29:
        	Error Trace:	parser_test.go:29
        	            				java_parser_test.go:31
        	Error:      	Not equal:
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestExternalParserCommonCasesForMaxCompute
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 20 [running]:
testing.tRunner.func1(0xc0001f0100)
	/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0xa4b360, 0xc000141160)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
sqlflow.org/sqlflow/pkg/parser/external.commonThirdPartyCases(0xb64b60, 0xc00009d600, 0xc000177f50)
	/root/go/src/sqlflow.org/sqlflow/pkg/parser/external/parser_test.go:30 +0x1a22
sqlflow.org/sqlflow/pkg/parser/external.TestExternalParserCommonCasesForMaxCompute(0xc0001f0100)
	/root/go/src/sqlflow.org/sqlflow/pkg/parser/external/java_parser_test.go:31 +0x76
testing.tRunner(0xc0001f0100, 0xac4ba8)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350
exit status 2
FAIL	sqlflow.org/sqlflow/pkg/parser/external	4.223s
```

**Comment by tonyyang-svail** [comment]
We have switched the official MaxCompute parser, so this issue no longer exists.
