### ISSUE TITLE
DeepEmbeddingClusterModel 例子中，batch_size 设置稍大，sqlflowserver 会停止工作。 

### ISSUE THREAD

**Issue by llxxxll** [sql-machine-learning/sqlflow#1676]
batch_size = 16  没问题
batch_size = 256 报错如下
```
==========Output==========
2020-01-10 03:15:29.235201 Start pre_train.
2020-01-10 03:15:29.304160 Finished dataset transform.
2020-01-10 03:15:29.318769 Training auto-encoder.
Epoch 1/100
2/2 - 2s - loss: 0.0718
Epoch 2/100
2/2 - 0s - loss: 0.0426
Epoch 3/100
2/2 - 0s - loss: 0.0197
Epoch 4/100
2/2 - 0s - loss: 0.0241
Epoch 5/100
2/2 - 0s - loss: 0.0196
Epoch 6/100
2/2 - 0s - loss: 0.0130
Epoch 7/100
2/2 - 0s - loss: 0.0134
Epoch 8/100
2/2 - 0s - loss: 0.0137
2020-01-10 03:15:33.213796 Calculating encoded_input.
2020-01-10 03:15:34.331437 Done pre-train.
Traceback (most recent call last):
  File "<stdin>", line 597, in <module>
  File "/root/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/train.py", line 196, in train
    batch_size, epochs, verbose, metric_names)
  File "/root/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/train.py", line 83, in keras_train_and_save
    classifier.sqlflow_train_loop(train_dataset.map(flatten))
  File "/usr/local/lib/python3.6/dist-packages/sqlflow_models-0.0.1-py3.6.egg/sqlflow_models/deep_embedding_cluster.py", line 209, in sqlflow_train_loop
  File "/usr/local/lib/python3.6/dist-packages/sqlflow_models-0.0.1-py3.6.egg/sqlflow_models/deep_embedding_cluster.py", line 192, in init_centroids
  File "/usr/local/lib/python3.6/dist-packages/sklearn/cluster/_kmeans.py", line 1008, in fit_predict
    return self.fit(X, sample_weight=sample_weight).labels_
  File "/usr/local/lib/python3.6/dist-packages/sklearn/cluster/_kmeans.py", line 863, in fit
    _num_samples(X), self.n_clusters))
ValueError: n_samples=2 should be >= n_clusters=3

```

**Comment by BlackPoint-CX** [comment]
> batch_size = 16 没问题
> batch_size = 256 报错如下
> 
> ```
> ==========Output==========
> 2020-01-10 03:15:29.235201 Start pre_train.
> 2020-01-10 03:15:29.304160 Finished dataset transform.
> 2020-01-10 03:15:29.318769 Training auto-encoder.
> Epoch 1/100
> 2/2 - 2s - loss: 0.0718
> Epoch 2/100
> 2/2 - 0s - loss: 0.0426
> Epoch 3/100
> 2/2 - 0s - loss: 0.0197
> Epoch 4/100
> 2/2 - 0s - loss: 0.0241
> Epoch 5/100
> 2/2 - 0s - loss: 0.0196
> Epoch 6/100
> 2/2 - 0s - loss: 0.0130
> Epoch 7/100
> 2/2 - 0s - loss: 0.0134
> Epoch 8/100
> 2/2 - 0s - loss: 0.0137
> 2020-01-10 03:15:33.213796 Calculating encoded_input.
> 2020-01-10 03:15:34.331437 Done pre-train.
> Traceback (most recent call last):
>   File "<stdin>", line 597, in <module>
>   File "/root/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/train.py", line 196, in train
>     batch_size, epochs, verbose, metric_names)
>   File "/root/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/train.py", line 83, in keras_train_and_save
>     classifier.sqlflow_train_loop(train_dataset.map(flatten))
>   File "/usr/local/lib/python3.6/dist-packages/sqlflow_models-0.0.1-py3.6.egg/sqlflow_models/deep_embedding_cluster.py", line 209, in sqlflow_train_loop
>   File "/usr/local/lib/python3.6/dist-packages/sqlflow_models-0.0.1-py3.6.egg/sqlflow_models/deep_embedding_cluster.py", line 192, in init_centroids
>   File "/usr/local/lib/python3.6/dist-packages/sklearn/cluster/_kmeans.py", line 1008, in fit_predict
>     return self.fit(X, sample_weight=sample_weight).labels_
>   File "/usr/local/lib/python3.6/dist-packages/sklearn/cluster/_kmeans.py", line 863, in fit
>     _num_samples(X), self.n_clusters))
> ValueError: n_samples=2 should be >= n_clusters=3
> ```

这个报错看起来是因为训练数据样本数太少(2), 少于需要聚类的数量(3). 可以增大训练数据样本量吗?

**Comment by shendiaomo** [comment]
> > batch_size = 16 没问题
> > batch_size = 256 报错如下
> > ```
> > ==========Output==========
> > 2020-01-10 03:15:29.235201 Start pre_train.
> > 2020-01-10 03:15:29.304160 Finished dataset transform.
> > 2020-01-10 03:15:29.318769 Training auto-encoder.
> > Epoch 1/100
> > 2/2 - 2s - loss: 0.0718
> > Epoch 2/100
> > 2/2 - 0s - loss: 0.0426
> > Epoch 3/100
> > 2/2 - 0s - loss: 0.0197
> > Epoch 4/100
> > 2/2 - 0s - loss: 0.0241
> > Epoch 5/100
> > 2/2 - 0s - loss: 0.0196
> > Epoch 6/100
> > 2/2 - 0s - loss: 0.0130
> > Epoch 7/100
> > 2/2 - 0s - loss: 0.0134
> > Epoch 8/100
> > 2/2 - 0s - loss: 0.0137
> > 2020-01-10 03:15:33.213796 Calculating encoded_input.
> > 2020-01-10 03:15:34.331437 Done pre-train.
> > Traceback (most recent call last):
> >   File "<stdin>", line 597, in <module>
> >   File "/root/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/train.py", line 196, in train
> >     batch_size, epochs, verbose, metric_names)
> >   File "/root/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/train.py", line 83, in keras_train_and_save
> >     classifier.sqlflow_train_loop(train_dataset.map(flatten))
> >   File "/usr/local/lib/python3.6/dist-packages/sqlflow_models-0.0.1-py3.6.egg/sqlflow_models/deep_embedding_cluster.py", line 209, in sqlflow_train_loop
> >   File "/usr/local/lib/python3.6/dist-packages/sqlflow_models-0.0.1-py3.6.egg/sqlflow_models/deep_embedding_cluster.py", line 192, in init_centroids
> >   File "/usr/local/lib/python3.6/dist-packages/sklearn/cluster/_kmeans.py", line 1008, in fit_predict
> >     return self.fit(X, sample_weight=sample_weight).labels_
> >   File "/usr/local/lib/python3.6/dist-packages/sklearn/cluster/_kmeans.py", line 863, in fit
> >     _num_samples(X), self.n_clusters))
> > ValueError: n_samples=2 should be >= n_clusters=3
> > ```
> 
> 这个报错看起来是因为训练数据样本数太少(2), 少于需要聚类的数量(3). 可以增大训练数据样本量吗?

不对啊，如果是这个原因，batch_size=16的时候也会报错

**Comment by BlackPoint-CX** [comment]
> > > batch_size = 16 没问题
> > > batch_size = 256 报错如下
> > > ```
> > > ==========Output==========
> > > 2020-01-10 03:15:29.235201 Start pre_train.
> > > 2020-01-10 03:15:29.304160 Finished dataset transform.
> > > 2020-01-10 03:15:29.318769 Training auto-encoder.
> > > Epoch 1/100
> > > 2/2 - 2s - loss: 0.0718
> > > Epoch 2/100
> > > 2/2 - 0s - loss: 0.0426
> > > Epoch 3/100
> > > 2/2 - 0s - loss: 0.0197
> > > Epoch 4/100
> > > 2/2 - 0s - loss: 0.0241
> > > Epoch 5/100
> > > 2/2 - 0s - loss: 0.0196
> > > Epoch 6/100
> > > 2/2 - 0s - loss: 0.0130
> > > Epoch 7/100
> > > 2/2 - 0s - loss: 0.0134
> > > Epoch 8/100
> > > 2/2 - 0s - loss: 0.0137
> > > 2020-01-10 03:15:33.213796 Calculating encoded_input.
> > > 2020-01-10 03:15:34.331437 Done pre-train.
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 597, in <module>
> > >   File "/root/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/train.py", line 196, in train
> > >     batch_size, epochs, verbose, metric_names)
> > >   File "/root/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/train.py", line 83, in keras_train_and_save
> > >     classifier.sqlflow_train_loop(train_dataset.map(flatten))
> > >   File "/usr/local/lib/python3.6/dist-packages/sqlflow_models-0.0.1-py3.6.egg/sqlflow_models/deep_embedding_cluster.py", line 209, in sqlflow_train_loop
> > >   File "/usr/local/lib/python3.6/dist-packages/sqlflow_models-0.0.1-py3.6.egg/sqlflow_models/deep_embedding_cluster.py", line 192, in init_centroids
> > >   File "/usr/local/lib/python3.6/dist-packages/sklearn/cluster/_kmeans.py", line 1008, in fit_predict
> > >     return self.fit(X, sample_weight=sample_weight).labels_
> > >   File "/usr/local/lib/python3.6/dist-packages/sklearn/cluster/_kmeans.py", line 863, in fit
> > >     _num_samples(X), self.n_clusters))
> > > ValueError: n_samples=2 should be >= n_clusters=3
> > > ```
> > 
> > 
> > 这个报错看起来是因为训练数据样本数太少(2), 少于需要聚类的数量(3). 可以增大训练数据样本量吗?
> 
> 不对啊，如果是这个原因，batch_size=16的时候也会报错

这个报错发生在init_centroids方法中, 由KMeans做聚类中心点初始化时抛出的. 我查了下stackoverflow, 
[sklearn.cluster.KMeans 报错 ValueError: n_samples=1 should be >= n_clusters=10](https://blog.csdn.net/cy_tec/article/details/77931820) 
[KMeans clustering - Value error: n_samples=1 should be >= n_cluster](https://stackoverflow.com/questions/54833924/kmeans-clustering-value-error-n-samples-1-should-be-n-cluster)
好像都是因为输入数据的维度被误输入为1维, 但是这和我们的情况不符, 因为我们的情况是n_samples=2, 而输入维度误为1维的话, 应该是n_samples=1.

能不能提供下对应的数据集我本地复现下?

**Comment by llxxxll** [comment]
datasets:
https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/tutorial/apsara2019/activepower_clustering/activepower.sql

docker image:
```
sqlflow/sqlflow:latest
```

train sql:
```sql
%%sqlflow
SELECT m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12,m13,m14,m15,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25,m26,m27,m28,m29,m30,m31,m32,m33,m34,m35,m36,m37,m38,m39,m40,m41,m42,m43,m44,m45,m46,m47,m48 
FROM activepower.train
TO TRAIN sqlflow_models.DeepEmbeddingClusterModel
WITH
    model.n_clusters=3,
    model.pretrain_epochs=100,
    model.train_max_iters=800,
    model.pretrain_lr=1,
    model.train_lr=0.01,
    train.batch_size=256
COLUMN m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12,m13,m14,m15,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25,m26,m27,m28,m29,m30,m31,m32,m33,m34,m35,m36,m37,m38,m39,m40,m41,m42,m43,m44,m45,m46,m47,m48
INTO sqlflow_models.my_customized_model;
```
@BlackPoint-CX
