### ISSUE TITLE
SQLFlow server raise error at launching

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#1728]
The error logs:

``` text
2020/01/16 21:59:06 ExtractDocString failed:  exit status 1 Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'extract_docstring'

2020/01/16 21:59:06 ExtractDocString failed: invalid character 'T' looking for beginning of value Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'extract_docstring'

2020/01/16 21:59:06 Launch server with insecure mode.
2020/01/16 21:59:06 Server Started at :50051
```

**Comment by shendiaomo** [comment]
This is actually a warning that doesn't affect the normal running. I think we may update the Dockfile to fix this.

**Comment by wangkuiyi** [comment]
@shendiaomo Thanks for the update. I agree that we fix the issue by removing this warning. Any idea or suggestion how?

- The official Docker image do not warn. In addition, I removed the call to `ExtractDocString` from `init` in https://github.com/sql-machine-learning/sqlflow/pull/1796, so there will not be any warning at SQLFlow launching in any case.

- @Yancey1989 noticed that the DataWorks deployment uses another Dockerfile to build the on-premise image, we'll fix that later.
