### ISSUE TITLE
Feature derivation panic on error SQL

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#1828]
```
repl -datasource "mysql://root:root@tcp(127.0.0.1:3306)/?maxAllowedPacket=0" -e 'select * from titanic.train
to train xgboost.gbtree
with
    objective="multi:softprob",
    train.num_boost_round = 30,
    eta = 0.4,
    num_class = 2
LABEL class
INTO sqlflow_models.my_xgboost_model;'
```
panic on nil pointer reference in feature derivation package. I suspect it is due to the table `titanic.train` doesn't contain `LABEL class`.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xed0206]

goroutine 15 [running]:
sqlflow.org/sqlflow/pkg/step/feature.deriveLabel(0xc0002c8460, 0xc000312d50)
	/go/src/sqlflow.org/sqlflow/pkg/step/feature/derivation.go:501 +0x116
sqlflow.org/sqlflow/pkg/step/feature.InferFeatureColumns(0xc0002c8460, 0xc000407c80, 0x39, 0x0, 0x0)
	/go/src/sqlflow.org/sqlflow/pkg/step/feature/derivation.go:297 +0x5a6
sqlflow.org/sqlflow/pkg/sql.generateTrainStmtWithInferredColumns(0xc00033a180, 0xc000407c80, 0x39, 0x1, 0x0, 0x0, 0x0)
	/go/src/sqlflow.org/sqlflow/pkg/sql/ir_generator.go:48 +0x97
sqlflow.org/sqlflow/pkg/sql.runSQLProgram(0xc00049a4c0, 0xc000112340, 0xce, 0xc000180990, 0x0, 0x0, 0xc0001149a0, 0x0, 0x0)
	/go/src/sqlflow.org/sqlflow/pkg/sql/executor_ir.go:183 +0x6e8
sqlflow.org/sqlflow/pkg/sql.RunSQLProgram.func1(0xc00049a4c0, 0xc0001149a0, 0xc000112340, 0xce, 0x0, 0x0)
	/go/src/sqlflow.org/sqlflow/pkg/sql/executor_ir.go:63 +0x215
created by sqlflow.org/sqlflow/pkg/sql.RunSQLProgram
	/go/src/sqlflow.org/sqlflow/pkg/sql/executor_ir.go:54 +0x14c
```

This issue should be fixed soon since users are likely submitting errored SQLs, and the errored SQLs shouldn't make our server crash.

**Comment by tonyyang-svail** [comment]
By changing `LABEL class` to `LABEL SURVIVED`, a similar error occurs.

By changing `LABEL SURVIVED` to `LABEL survived`, the run is successful.
