### ISSUE TITLE
Predicting doesn't work when there're indicator or embedding columns

### ISSUE THREAD

**Issue by shendiaomo** [sql-machine-learning/sqlflow#1957]
**Description**
Predicting doesn't work when there're indicator or embedding columns
**Reproduction Steps**
```sql
-- train
SELECT f9, target FROM housing.train
TO TRAIN DNNRegressor WITH
     model.hidden_units = [10, 20]
COLUMN EMBEDDING(CATEGORY_ID(f9, 1000), 2, "sum")
LABEL target
INTO housing.dnn_model;
-- predict
SELECT f9, target FROM housing.test
TO PREDICT housing.predict.class USING housing.dnn_model;
```
The predicting statement will raise a python exception:
```
Start predicting using estimator model...
Traceback (most recent call last):
  File "<stdin>", line 61, in <module>
  File "/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/predict.py", line 273, in pred
    pai_table)
  File "/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/predict.py", line 208, in estimator_predict
    result = predict(features)
  File "/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/predict.py", line 202, in predict
    examples=tf.constant([example.SerializeToString()]))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 1081, in __call__
    return self._call_impl(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 1121, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Name: <unknown>, Key: f9, Index: 0.  Data types don't match. Expected type: int64, Actual type: float
	 [[node ParseExample/ParseExample (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference_pruned_599]
```
The reason is we convert `int`s to `float`s: https://github.com/sql-machine-learning/sqlflow/blob/e6771627ec2af25152f7c5c126e445cffda4ef76/python/sqlflow_submitter/tensorflow/predict.py#L191-L193
The conversion is to make the numeric columns work. 
**Expected Behavior**
We did not specify the `dtype` argument in SQLFlow, which defaults to `float32`. The best fix is to specify it as the data type of the field.
**Screenshots**
![image](https://user-images.githubusercontent.com/4180295/76078828-66c84200-5fde-11ea-8cc6-cc09463adbbd.png)

**Comment by Yancey0623** [comment]
LinearClassifier Prediction also failed, the reproduce SQL:

``` sql
SELECT amount / 25691.16 amount, 
       v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, 
       v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27, v28,    
       class FROM alifin_jtest_dev.sqlflow_fraud_detection
TO TRAIN LinearClassifier WITH
  train.batch_size=2048,
  model.optimizer=FtrlOptimizer,
  optimizer.learning_rate=0.01
LABEL class
INTO sqlflow_e2etest_fraud_lr_model;

-- 2 PREDCIT
SELECT * FROM alifin_jtest_dev.sqlflow_fraud_detection_pred
TO PREDICT alifin_jtest_dev.sqlflow_e2etest_fraud_detection_predict.class
USING sqlflow_e2etest_fraud_lr_model;
```

Error logs:

``` text
    self.writer.write(self.rows, self.writer_indices)
  File "/usr/lib/python2.7/site-packages/paiio/python/python_io/table_writer.py", line 35, in write
    self._writer.write(values=values, col_indices=indices)
  File "/usr/lib64/python2.7/site-packages/common_io/table.py", line 182, in write
    list(tuple(v) for v in values), tuple(col_indices), allow_type_cast)
  File "/usr/lib64/python2.7/site-packages/common_io/table.py", line 204, in _write
    raise Exception(err)
Exception: Can't convert Python object because of type mismatching. [Convert to <type 'int'> for column 0]. Detailed message: invalid literal for long() with base 10
```

**Comment by typhoonzero** [comment]
@Yancey1989 the case you provided seems not related to this issue, you need to use exactly the same fields when doing prediction:

```
SELECT *amount / 25691.16 amount, 
       v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, 
       v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27, v28,    
       class FROM alifin_jtest_dev.sqlflow_fraud_detection_pred
TO PREDICT alifin_jtest_dev.sqlflow_e2etest_fraud_detection_predict.class
USING sqlflow_e2etest_fraud_lr_model;
```

**Comment by typhoonzero** [comment]
Still need to fix this issue when using deep and wide model
