### ISSUE TITLE
CI fail if removing -p 1 from gotest

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#2614]
```
=== RUN   TestGetServerAddrFromEnv
2020/07/03 06:35:44 Server Started at :50051
--- FAIL: TestGetServerAddrFromEnv (0.10s)
    main_test.go:981: 
        	Error Trace:	main_test.go:981
        	Error:      	"Database changed to iris
        	            	sqlflow> show tables;
        	            	+----------------+
        	            	| TABLES IN IRIS |
        	            	+----------------+
        	            	| iris_empty     |
        	            	| predict        |
        	            	| test           |
        	            	| test_dense     |
        	            	| train          |
        	            	| train_dense    |
        	            	+----------------+
        	            	" does not contain "
        	            	+----------------+
        	            	| TABLES IN IRIS |
        	            	+----------------+
        	            	| iris_empty     |
        	            	| test           |
        	            	| test_dense     |
        	            	| train          |
        	            	| train_dense    |
        	            	+----------------+"
        	Test:       	TestGetServerAddrFromEnv
```

**Comment by wangkuiyi** [comment]
More cases for your reference


```
=== RUN   TestRepl
2020/07/03 07:05:31 Server Started at :50051
--- FAIL: TestRepl (16.09s)
    main_test.go:185: 
        	Error Trace:	main_test.go:185
        	Error:      	"Database changed to iris
        	            	sqlflow> 
        	            	
        	            	show tables;
        	            	+----------------+
        	            	| TABLES IN IRIS |
        	            	+----------------+
        	            	| iris_empty     |
        	            	| predict        |
        	            	| test           |
        	            	| test_dense     |
        	            	| train          |
        	            	| train_dense    |
        	            	+----------------+
        	            	sqlflow> 
        	            	select * from train to train DNNClassifier
        	            	WITH model.hidden_units=[10,10], model.n_classes=3, validation.select="select * from test"
        	            	label class
        	            	INTO sqlflow_models.repl_dnn_model;
        	            	Start training using estimator model...
        	            	
        	            	{'accuracy': 0.2, 'average_loss': 1.0719784, 'loss': 1.0719784, 'global_step': 110}
        	            	
        	            	Done training, model exported to: model_save/1593759946
        	            	
        	            	Done training
        	            	
        	            	Database changed to sqlflow_models
        	            	sqlflow> show tables;
        	            	+--------------------------+
        	            	| TABLES IN SQLFLOW MODELS |
        	            	+--------------------------+
        	            	| my_dnn_model             |
        	            	| mytest_model             |
        	            	| repl_dnn_model           |
        	            	| repl_xgb_model           |
        	            	+--------------------------+
        	            	" does not contain "
        	            	+----------------+
        	            	| TABLES IN IRIS |
        	            	+----------------+
        	            	| iris_empty     |
        	            	| test           |
        	            	| test_dense     |
        	            	| train          |
        	            	| train_dense    |
        	            	+----------------+"
        	Test:       	TestRepl
=== RUN   TestReplWithoutSemicolon
2020/07/03 07:05:48 Server Started at :50051
--- PASS: TestReplWithoutSemicolon (12.88s)
=== RUN   TestMain
2020/07/03 07:06:00 Server Started at :50051
--- FAIL: TestMain (0.12s)
    main_test.go:238: 
        	Error Trace:	main_test.go:238
        	Error:      	"Database changed to iris
        	            	sqlflow> show tables;
        	            	+----------------+
        	            	| TABLES IN IRIS |
        	            	+----------------+
        	            	| iris_empty     |
        	            	| predict        |
        	            	| test           |
        	            	| test_dense     |
        	            	| train          |
        	            	| train_dense    |
        	            	+----------------+
        	            	" does not contain "
        	            	+----------------+
        	            	| TABLES IN IRIS |
        	            	+----------------+
        	            	| iris_empty     |
        	            	| test           |
        	            	| test_dense     |
        	            	| train          |
        	            	| train_dense    |
        	            	+----------------+"
        	Test:       	TestMain
=== RUN   TestGetDataSource
--- PASS: TestGetDataSource (0.00s)
=== RUN   TestMainFastFail
2020/07/03 07:06:01 Server Started at :50051
--- PASS: TestMainFastFail (0.09s)
=== RUN   TestReadStmt
--- PASS: TestReadStmt (0.00s)
=== RUN   TestPromptState
--- PASS: TestPromptState (0.00s)
=== RUN   TestInputNavigation
--- PASS: TestInputNavigation (0.00s)
=== RUN   TestComplete
--- PASS: TestComplete (0.00s)
=== RUN   TestGetTerminalColumnSize
--- PASS: TestGetTerminalColumnSize (0.00s)
=== RUN   TestEmacsKeyBindings
acsKeyBindings (0.00s)
=== RUN   TestDotEnv
--- PASS: TestDotEnv (0.00s)
=== RUN   TestStdinParser
--- PASS: TestStdinParser (0.00s)
=== RUN   TestGetServerAddrFromEnv
2020/07/03 07:06:01 Server Started at :50051
--- FAIL: TestGetServerAddrFromEnv (0.09s)
    main_test.go:981: 
        	Error Trace:	main_test.go:981
        	Error:      	"Database changed to iris
        	            	sqlflow> show tables;
        	            	+----------------+
        	            	| TABLES IN IRIS |
        	            	+----------------+
        	            	| iris_empty     |
        	            	| predict        |
        	            	| test           |
        	            	| test_dense     |
        	            	| train          |
        	            	| train_dense    |
        	            	+----------------+
        	            	" does not contain "
        	            	+----------------+
        	            	| TABLES IN IRIS |
        	            	+----------------+
        	            	| iris_empty     |
        	            	| test           |
        	            	| test_dense     |
        	            	| train          |
        	            	| train_dense    |
        	            	+----------------+"
        	Test:       	TestGetServerAddrFromEnv
=== RUN   TestIsExitStmt
--- PASS: TestIsExitStmt (0.00s)
```

**Comment by typhoonzero** [comment]
Current errors in the experiment: https://github.com/sql-machine-learning/sqlflow/pull/2618, we need to find out the reason and solution.


```
=== RUN   TestFeatureDerivationNoColumnClause
coverage: 25.5% of statements
panic: test timed out after 2m0s

goroutine 51 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1377 +0xdf
created by time.goFunc
	/usr/local/go/src/time/sleep.go:168 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0003aa300, 0xe20c28, 0x23, 0xe53ee0, 0x48a601)
	/usr/local/go/src/testing/testing.go:961 +0x377
testing.runTests.func1(0xc0002a4000)
	/usr/local/go/src/testing/testing.go:1202 +0x78
testing.tRunner(0xc0002a4000, 0xc000185d88)
	/usr/local/go/src/testing/testing.go:909 +0xc9
testing.runTests(0xc0000c19a0, 0x180e260, 0xe, 0xe, 0x0)
	/usr/local/go/src/testing/testing.go:1200 +0x2a7
testing.(*M).Run(0xc000104600, 0x0)
	/usr/local/go/src/testing/testing.go:1117 +0x176
main.main()
	_testmain.go:126 +0x1c1

goroutine 20 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1846fa0)
	/root/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
	/root/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x26f

goroutine 6 [IO wait]:
internal/poll.runtime_pollWait(0x7f51a4500508, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0003f4098, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0003f4080, 0xc0003fe000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc0003f4080, 0xc0003fe000, 0x1000, 0x1000, 0xc0003d5630, 0xc0003f4080, 0xc0003f4098)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0003f8000, 0xc0003fe000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x68
github.com/go-sql-driver/mysql.(*buffer).fill(0xc00036e240, 0x4, 0xc0003d5310, 0x6cf193)
	/root/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/buffer.go:90 +0x13c
github.com/go-sql-driver/mysql.(*buffer).readNext(0xc00036e240, 0x4, 0x28, 0x0, 0x0, 0x24, 0x24)
	/root/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/buffer.go:119 +0x9c
github.com/go-sql-driver/mysql.(*mysqlConn).readPacket(0xc00036e240, 0xc00000006, 0x28, 0x1000, 0xc000020000, 0xc0003fe000)
	/root/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/packets.go:31 +0x91
github.com/go-sql-driver/mysql.(*mysqlConn).readResultSetHeaderPacket(0xc00036e240, 0x1868c03, 0xc0000acb40, 0x23)
	/root/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/packets.go:537 +0x2f
github.com/go-sql-driver/mysql.(*mysqlConn).query(0xc00036e240, 0xc0000acb40, 0x23, 0x1868c98, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connection.go:390 +0x266
github.com/go-sql-driver/mysql.(*mysqlConn).QueryContext(0xc00036e240, 0xf497a0, 0xc0000b0010, 0xc0000acb40, 0x23, 0x1868c98, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connection.go:512 +0x104
database/sql.ctxDriverQuery(0xf497a0, 0xc0000b0010, 0x7f51a44b3078, 0xc00036e240, 0x0, 0x0, 0xc0000acb40, 0x23, 0x1868c98, 0x0, ...)
	/usr/local/go/src/database/sql/ctxutil.go:48 +0x227
database/sql.(*DB).queryDC.func1()
	/usr/local/go/src/database/sql/sql.go:1592 +0x1db
database/sql.withLock(0xf38f00, 0xc000105f80, 0xc0003d57a8)
	/usr/local/go/src/database/sql/sql.go:3184 +0x6d
database/sql.(*DB).queryDC(0xc0003c6000, 0xf497a0, 0xc0000b0010, 0x0, 0x0, 0xc000105f80, 0xc000257f90, 0xc0000acb40, 0x23, 0x0, ...)
	/usr/local/go/src/database/sql/sql.go:1587 +0x5dd
database/sql.(*DB).query(0xc0003c6000, 0xf497a0, 0xc0000b0010, 0xc0000acb40, 0x23, 0x0, 0x0, 0x0, 0xc00014a001, 0x23, ...)
	/usr/local/go/src/database/sql/sql.go:1570 +0x136
database/sql.(*DB).QueryContext(0xc0003c6000, 0xf497a0, 0xc0000b0010, 0xc0000acb40, 0x23, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/database/sql/sql.go:1547 +0xd1
database/sql.(*DB).Query(...)
	/usr/local/go/src/database/sql/sql.go:1561
sqlflow.org/sqlflow/go/verifier.FetchSamples(0xc000368540, 0xe156d6, 0x18, 0x6c1800, 0xc00036e240, 0x8)
	/root/go/src/sqlflow.org/sqlflow/go/verifier/verifier.go:51 +0x126
sqlflow.org/sqlflow/go/ir.InferFeatureColumns(0xc0003d5eb0, 0xc000368540, 0x0, 0x0)
	/root/go/src/sqlflow.org/sqlflow/go/ir/derivation.go:344 +0xb2
sqlflow.org/sqlflow/go/ir.TestFeatureDerivationNoColumnClause(0xc0003aa300)
	/root/go/src/sqlflow.org/sqlflow/go/ir/derivation_test.go:348 +0x45c
testing.tRunner(0xc0003aa300, 0xe53ee0)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350

goroutine 8 [select]:
database/sql.(*DB).connectionResetter(0xc0003c6000, 0xf49760, 0xc000080580)
	/usr/local/go/src/database/sql/sql.go:1065 +0xfb
created by database/sql.OpenDB
	/usr/local/go/src/database/sql/sql.go:723 +0x193

goroutine 7 [select]:
database/sql.(*DB).connectionOpener(0xc0003c6000, 0xf49760, 0xc000080580)
	/usr/local/go/src/database/sql/sql.go:1052 +0xe8
created by database/sql.OpenDB
	/usr/local/go/src/database/sql/sql.go:722 +0x15d

goroutine 50 [select]:
github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1(0xc0003fa000, 0xc00036e240, 0xc0003fc000)
	/root/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connection.go:621 +0xbf
created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher
	/root/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connection.go:618 +0xbe
```
