### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by maker-dong** [sql-machine-learning/sqlflow#3124]
**Description**
在Kubernetes中安装SQLFlow，运行iris-dnn时，会报错ModuleNotFoundError
详情如下：
````
_MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "failed /usr/local/bin/python /tmp/sqlflow.py598475276, exit status 1 Traceback (most recent call last):
  File "/tmp/sqlflow.py598475276", line 5, in <module>
    import couler.argo as couler
  File "/usr/lib/python3.8/site-packages/couler/__init__.py", line 14, in <module>
    from couler.argo import *  # noqa: F401, F403
  File "/usr/lib/python3.8/site-packages/couler/argo.py", line 19, in <module>
    from kubernetes import client as k8s_client
  File "/usr/lib/python3.8/site-packages/kubernetes/__init__.py", line 19, in <module>
    import kubernetes.client
  File "/usr/lib/python3.8/site-packages/kubernetes/client/__init__.py", line 20, in <module>
    from kubernetes.client.api.admissionregistration_api import AdmissionregistrationApi
  File "/usr/lib/python3.8/site-packages/kubernetes/client/api/__init__.py", line 6, in <module>
    from kubernetes.client.api.admissionregistration_api import AdmissionregistrationApi
  File "/usr/lib/python3.8/site-packages/kubernetes/client/api/admissionregistration_api.py", line 18, in <module>
    import six
ModuleNotFoundError: No module named 'six'
"
	debug_error_string = "{"created":"@1614668413.387105297","description":"Error received from peer ipv4:10.1.14.152:50051","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"failed /usr/local/bin/python /tmp/sqlflow.py598475276, exit status 1 Traceback (most recent call last):\n  File "/tmp/sqlflow.py598475276", line 5, in <module>\n    import couler.argo as couler\n  File "/usr/lib/python3.8/site-packages/couler/__init__.py", line 14, in <module>\n    from couler.argo import *  # noqa: F401, F403\n  File "/usr/lib/python3.8/site-packages/couler/argo.py", line 19, in <module>\n    from kubernetes import client as k8s_client\n  File "/usr/lib/python3.8/site-packages/kubernetes/__init__.py", line 19, in <module>\n    import kubernetes.client\n  File "/usr/lib/python3.8/site-packages/kubernetes/client/__init__.py", line 20, in <module>\n    from kubernetes.client.api.admissionregistration_api import AdmissionregistrationApi\n  File "/usr/lib/python3.8/site-packages/kubernetes/client/api/__init__.py", line 6, in <module>\n    from kubernetes.client.api.admissionregistration_api import AdmissionregistrationApi\n  File "/usr/lib/python3.8/site-packages/kubernetes/client/api/admissionregistration_api.py", line 18, in <module>\n    import six\nModuleNotFoundError: No module named 'six'\n","grpc_status":2}"
>
````

**Environment :**
 - Kubernetes v1.18.0

**Comment by Yancey0623** [comment]
感谢 @DongTL 反馈 ，这是打包 SQLFlow server 镜像时的一个 bug，已修复。 请等待 [这个](https://github.com/sql-machine-learning/sqlflow/actions/runs/638758269) CI 任务运行完毕，即可拉取最新的镜像来修复这个问题。
