### ISSUE TITLE
ModuleNotFoundError: No module named 'six' .After Setup SQLFlow Playground with Single-user Mode, execute %%sqlflow,got an error.

### ISSUE THREAD

**Issue by hizzyishome** [sql-machine-learning/sqlflow#3130]
**Description**
install location with doc [single-user mode](https://sql-machine-learning.github.io/sqlflow/doc/run/kubernetes/#setup-sqlflow-playground-with-single-user-mode)
when all the pod ready
![image](https://user-images.githubusercontent.com/8719736/118441204-6f0c2900-b71b-11eb-8d17-1183af119c2e.png)

run the sql from tutorial/iris-dnn  
`%%sqlflow
SELECT * FROM iris.train TO TRAIN DNNClassifier WITH
  model.n_classes = 3,
  model.hidden_units = [10, 10],
  train.epoch = 10
COLUMN sepal_length, sepal_width, petal_length, petal_width
LABEL class
INTO sqlflow_models.my_dnn_model;`

it gives as follow:
`
_MultiThreadedRendezvous                  Traceback (most recent call last)
<ipython-input-13-d1a9a95e2bcd> in <module>
----> 1 get_ipython().run_cell_magic('sqlflow', '', 'SELECT * FROM iris.train TO TRAIN DNNClassifier WITH\n  model.n_classes = 3,\n  model.hidden_units = [10, 10],\n  train.epoch = 10\nCOLUMN sepal_length, sepal_width, petal_length, petal_width\nLABEL class\nINTO sqlflow_models.my_dnn_model;\n')

/usr/lib/python3.8/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2357             with self.builtin_trap:
   2358                 args = (magic_arg_s, cell)
-> 2359                 result = fn(*args, **kwargs)
   2360             return result
   2361 

<decorator-gen-117> in execute(self, line, cell)

/usr/lib/python3.8/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

/usr/lib/python3.8/site-packages/sqlflow/magic.py in execute(self, line, cell)
     43 
     44         """
---> 45         return self.client.execute('\n'.join([line, cell]))
     46 
     47 def load_ipython_extension(ipython):

/usr/lib/python3.8/site-packages/sqlflow/client.py in execute(self, operation)
    147             # NOTE: raise exception to interrupt notebook execution. Or
    148             # the notebook will continue execute the next block.
--> 149             raise e
    150         except EnvExpanderError as e:
    151             raise e

/usr/lib/python3.8/site-packages/sqlflow/client.py in execute(self, operation)
    143         try:
    144             stream_response = self._stub.Run(self.sql_request(operation), timeout=DEFAULT_TIMEOUT)
--> 145             return self.display(stream_response)
    146         except grpc.RpcError as e:
    147             # NOTE: raise exception to interrupt notebook execution. Or

/usr/lib/python3.8/site-packages/sqlflow/client.py in display(self, stream_response)
    206         """Display stream response like log or table.row"""
    207         reader = StreamReader(stream_response)
--> 208         response, rtype = reader.read_one()
    209         compound_message = CompoundMessage()
    210         while True:

/usr/lib/python3.8/site-packages/sqlflow/client.py in read_one(self)
     35     def read_one(self):
     36         try:
---> 37             res = next(self._stream_response)
     38         except StopIteration:
     39             return (None, None)

/usr/lib/python3.8/site-packages/grpc/_channel.py in __next__(self)
    414 
    415     def __next__(self):
--> 416         return self._next()
    417 
    418     def _next(self):

/usr/lib/python3.8/site-packages/grpc/_channel.py in _next(self)
    704                     raise StopIteration()
    705                 elif self._state.code is not None:
--> 706                     raise self
    707 
    708 

_MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "failed /usr/local/bin/python /tmp/sqlflow.py209998603, exit status 1 Traceback (most recent call last):
  File "/tmp/sqlflow.py209998603", line 5, in <module>
    import couler.argo as couler
  File "/usr/lib/python3.8/site-packages/couler/__init__.py", line 14, in <module>
    from couler.argo import *  # noqa: F401, F403
  File "/usr/lib/python3.8/site-packages/couler/argo.py", line 19, in <module>
    from kubernetes import client as k8s_client
  File "/usr/lib/python3.8/site-packages/kubernetes/__init__.py", line 19, in <module>
    import kubernetes.client
  File "/usr/lib/python3.8/site-packages/kubernetes/client/__init__.py", line 20, in <module>
    from kubernetes.client.api.admissionregistration_api import AdmissionregistrationApi
  File "/usr/lib/python3.8/site-packages/kubernetes/client/api/__init__.py", line 6, in <module>
    from kubernetes.client.api.admissionregistration_api import AdmissionregistrationApi
  File "/usr/lib/python3.8/site-packages/kubernetes/client/api/admissionregistration_api.py", line 18, in <module>
    import six
ModuleNotFoundError: No module named 'six'
"
	debug_error_string = "{"created":"@1621232686.746967400","description":"Error received from peer ipv4:127.0.0.1:50051","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"failed /usr/local/bin/python /tmp/sqlflow.py209998603, exit status 1 Traceback (most recent call last):\n  File "/tmp/sqlflow.py209998603", line 5, in <module>\n    import couler.argo as couler\n  File "/usr/lib/python3.8/site-packages/couler/__init__.py", line 14, in <module>\n    from couler.argo import *  # noqa: F401, F403\n  File "/usr/lib/python3.8/site-packages/couler/argo.py", line 19, in <module>\n    from kubernetes import client as k8s_client\n  File "/usr/lib/python3.8/site-packages/kubernetes/__init__.py", line 19, in <module>\n    import kubernetes.client\n  File "/usr/lib/python3.8/site-packages/kubernetes/client/__init__.py", line 20, in <module>\n    from kubernetes.client.api.admissionregistration_api import AdmissionregistrationApi\n  File "/usr/lib/python3.8/site-packages/kubernetes/client/api/__init__.py", line 6, in <module>\n    from kubernetes.client.api.admissionregistration_api import AdmissionregistrationApi\n  File "/usr/lib/python3.8/site-packages/kubernetes/client/api/admissionregistration_api.py", line 18, in <module>\n    import six\nModuleNotFoundError: No module named 'six'\n","grpc_status":2}"
>
`
the image as follow:
![image](https://user-images.githubusercontent.com/8719736/118441970-8bf52c00-b71c-11eb-8c0d-68eba454e134.png)

but i execute :
`
import six
print (six.__version__)
`

it gives:
`1.15.0`

**Environment (Please complete the following information):**
 - OS:Windos 10
 - Browser:Chrome
 - docker destop 
 - Docker Engine : v20.10.6
 - Kubernetes: v1.19.7

**Comment by hizzyishome** [comment]
oh , I found here is a same issue: [ModuleNotFoundError #3124](https://github.com/sql-machine-learning/sqlflow/issues/3124)
 I've pull the newest image (nowtime 2021.05.17 14:56:07) but it doesn't work.

But there is a clue for me and you [pull request](https://github.com/sql-machine-learning/sqlflow/pull/3127/files)
he remove a line in Dockerfile:
`pk del --purge py3-pip && \`
![image](https://user-images.githubusercontent.com/8719736/118445086-90234880-b720-11eb-9f01-510ff1b24bdc.png)



so , I enter into my  k8s_server_sqlflow-server docker container
` docker  exec -itu root [your container id] /bin/bash`

then,execute this to install pip3 to fix lackness of model six
`apk add py3-pip`

finally it works well.
![image](https://user-images.githubusercontent.com/8719736/118445577-340cf400-b721-11eb-971f-b5253b3a011f.png)
