### ISSUE TITLE
Support Category variable on Label or Feature

### ISSUE THREAD

**Issue by Echo9573** [sql-machine-learning/sqlflow#588]
Q1: For some cases, the label is not an integer feature instead of category variable or enumeration variable, how should we write the Lable in sqlflow?

Q2: Sometimes, there are some category feature columns, the feature value is an enumeration char, just like"red, gray, green, blue......", and we don't know how many enumeration values, Usually, we can use [columns name].value_counts() in python to explore the specific quantity and values,  but, how should we write the feature column in sqlflow?

**Comment by tonyyang-svail** [comment]
Hi @Echo9573, thank you for submitting these useful feedbacks.

> Q1: For some cases, the label is not an integer feature instead of category variable or enumeration variable, how should we write the Lable in sqlflow?

I can think of two ways.

1) Tensorflow estimator usually supports [label_vocabulary](https://github.com/tensorflow/estimator/blob/master/tensorflow_estimator/python/estimator/canned/dnn.py#L693), you can try
    ```SQL
    SELECT ...
    TRAIN DNNClassifier
    WITH
       n_classes = 3,
       label_vocabulary = ["red", "green", "blue"]
    COLUMN ...
    ```
2) If there isn't too many classes, you can manually convert them in SQL. https://stackoverflow.com/questions/38567366/mapping-values-in-sql-select

> Q2: Sometimes, there are some category feature columns, the feature value is an enumeration char, just like"red, gray, green, blue......", and we don't know how many enumeration values, Usually, we can use [columns name].value_counts() in python to explore the specific quantity and values, but, how should we write the feature column in sqlflow?

SQLFlow currently doesn't support category column with vocabulary.

I am wondering how many enumerations are you dealing with?
- If it is small, we can port [categorical_column_with_vocabulary_list](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_list) to SQLFlow.
- If it is large, say a million, we would suggest converting the enumeration char to an id then use [`CATEGORY_ID`](https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/user_guide.md#category_id).

**Comment by Echo9573** [comment]
Thanks for you reply. 
For Q1-->way1, I have tried the solution way, but got an error feedback like the following:

```
"Traceback (most recent call last):

  File "<stdin>", line 147, in <module>

  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 359, in train

    loss = self._train_model(input_fn, hooks, saving_listeners)

  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1139, in _train_model

    return self._train_model_default(input_fn, hooks, saving_listeners)

  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1169, in _train_model_default

    features, labels, ModeKeys.TRAIN, self.config)

  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1127, in _call_model_fn

    model_fn_results = self._model_fn(features=features, **kwargs)

  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py", line 567, in _model_fn

    batch_norm=batch_norm)

  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py", line 394, in _dnn_model_fn_v2

    batch_norm=batch_norm)

  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py", line 267, in _dnn_model_fn_core

    logits=logits)

  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/head/base_head.py", line 285, in create_estimator_spec

    regularization_losses))

  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/head/multi_class_head.py", line 398, in _create_tpu_estimator_spec

    regularization_losses=regularization_losses)

  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/head/multi_class_head.py", line 252, in loss

    label_ids = self._processed_labels(logits, labels)

  File "/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/head/multi_class_head.py", line 221, in _processed_labels

    'vocabulary. Instead got {}'.format(labels.dtype))

ValueError: Labels dtype should be string if there is a vocabulary. Instead got <dtype: 'int64'>

StatusCode.UNKNOWN
training failed exit status 1"
```

I don't know how to deal with it.

**Comment by Yancey0623** [comment]
Hi @Echo9573, I think the `label_vocabulary` argument caused an SQLFlow bug, `label_vocabulary` need a string instead of int64, I created an issue to trace the bug: #593.

**Comment by Yancey0623** [comment]
Some additions to @tonyyang-svail , maybe we can also port [categorical_column_with_vocabulary_file](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file) to SQLFlow so that users can use a table as the input file, the SQLFlow syntax can be like:
``` sql
SELECT ...
TRAIN DNNClassifier
WITH
   n_classes = 3,
   label_vocabulary = ["red", "green", "blue"]
COLUMN  CATEGORY_ID_FROM_TABLE(class, VOCABULARY_TABLE)
```
