### ISSUE TITLE
Failed to drop table when storing predictions made by XGBoost into Hive 

### ISSUE THREAD

**Issue by BlackPoint-CX** [sql-machine-learning/sqlflow#739]
**Description**
When using local XGBoost model to make predictions and then trying to save the result into Hive, it throws exception as following : 
```
StatusCode.UNKNOWN
genXG failed executing drop table if exists SAMPLE_DATABASE.iris_xgb_predict.class;: 
"Error from server: TStatus({StatusCode:ERROR_STATUS InfoMessages:[*
org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: ParseException line 1:50 missing EOF at '.' near 'iris_xgb_predict':28:27 
org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:316 
org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:111 
org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:180 
org.apache.hive.service.cli.operation.Operation:run:Operation.java:257 
org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:410 
org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:391 sun.reflect.GeneratedMethodAccessor168:invoke::-1 sun.reflect.DelegatingMethodAccessorImpl:invoke:DelegatingMethodAccessorImpl.java:43 java.lang.reflect.Method:invoke:Method.java:498 
org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:78 
org.apache.hive.service.cli.session.HiveSessionProxy:access$000:HiveSessionProxy.java:36 
org.apache.hive.service.cli.session.HiveSessionProxy$1:run:HiveSessionProxy.java:63 java.security.AccessController:doPrivileged:AccessController.java:-2 javax.security.auth.Subject:doAs:Subject.java:422 
org.apache.hadoop.security.UserGroupInformation:doAs:UserGroupInformation.java:1867 
org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:59 com.sun.proxy.$Proxy17:executeStatement::-1 
org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:262 
org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:505 
org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1313 
org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1298 
org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39 
org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39 
org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:57 
org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286 java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1142 java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:617 java.lang.Thread:run:Thread.java:745 *
org.apache.hadoop.hive.ql.parse.ParseException:line 1:50 missing EOF at '.' near 'iris_xgb_predict':33:6 
org.apache.hadoop.hive.ql.parse.ParseDriver:parse:ParseDriver.java:213 
org.apache.hadoop.hive.ql.parse.ParseDriver:parse:ParseDriver.java:166 
org.apache.hadoop.hive.ql.Driver:compile:Driver.java:397 
org.apache.hadoop.hive.ql.Driver:compile:Driver.java:309 
org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1161 
org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1147 
org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:109] SqlState:0xc0002a8b40 ErrorCode:0xc0000c6bd4 ErrorMessage:0xc0002a8b50})"
```

**Reproduction Steps**
Train model step : 
```
%%sqlflow
SELECT *
FROM SAMPLE_DATABASE.iris_train
TRAIN xgboost.Estimator
WITH
	train.objective = "multi:softmax",
	train.num_class = 3,
	train.max_depth = 5,
	train.eta = 0.3,
	train.tree_method = "approx",
	train.num_round = 30
COLUMN sepal_length, sepal_width, petal_length, petal_width
LABEL class 
INTO SAMPLE_DATABASE.iris_xgb_model;
```
It works perfectly. Local model can be generated.

Make prediction step
```
%%sqlflow
SELECT *
FROM SAMPLE_DATABASE.iris_test
PREDICT SAMPLE_DATABASE.iris_xgb_predict.class
USING SAMPLE_DATABASE.iris_xgb_model;
```
Throw exception.

**Expected Behavior**
I supposes it should  behave like using DNNClassifier based on Tensorflow.

**Comment by Yancey0623** [comment]
Hi @BlackPoint-CX , How about changging 
``` sql
PREDICT SAMPLE_DATABASE.iris_xgb_predict.class 
```
 to
``` sql
PREDICT SAMPLE_DATABASE.iris_xgb_predict
```

**Comment by BlackPoint-CX** [comment]
> Hi @BlackPoint-CX , How about changging
> 
> ```sql
> PREDICT SAMPLE_DATABASE.iris_xgb_predict.class 
> ```
> 
> to
> 
> ```sql
> PREDICT SAMPLE_DATABASE.iris_xgb_predict
> ```

It doesn't work. Throw another exception as following :
```
WARNING: Logging before flag parsing goes to stderr.

W0829 18:37:42.081691 140218842502912 __init__.py:308] Limited tf.compat.v2.summary API due to missing TensorBoard installation.

W0829 18:37:42.103865 140218842502912 __init__.py:335] Limited tf.summary API due to missing TensorBoard installation.

Traceback (most recent call last):

  File "/home/luban/miniconda/envs/sqlflow-dev-py36/lib/python3.6/site-packages/sqlflow_submitter/xgboost/sqlflow_xgboost_main.py", line 78, in run_with_sqlflow

    predict(pred_fields)

  File "/home/luban/miniconda/envs/sqlflow-dev-py36/lib/python3.6/site-packages/launcher/main.py", line 105, in predict_pipeline

    with XGBoostPredictor(conf) as predictor:

  File "/home/luban/miniconda/envs/sqlflow-dev-py36/lib/python3.6/site-packages/launcher/predictor.py", line 19, in __init__

    assert self._ret_cols.result_column not in col_conf.append_columns, \

TypeError: argument of type 'NoneType' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<stdin>", line 15, in <module>

  File "/home/luban/miniconda/envs/sqlflow-dev-py36/lib/python3.6/site-packages/sqlflow_submitter/xgboost/sqlflow_xgboost_main.py", line 80, in run_with_sqlflow

    raise XGBoostError('XGBoost prediction task failed: %s' % e)

sqlflow_submitter.xgboost.common.XGBoostError: XGBoost prediction task failed: argument of type 'NoneType' is not iterable

StatusCode.UNKNOWN
exit status 1
```

**Comment by Yancey0623** [comment]
Please refine the prediction SQL to 
``` sql
SELECT *
FROM SAMPLE_DATABASE.iris_test
PREDICT SAMPLE_DATABASE.iris_xgb_predict
WITH
	pred.append_columns = [sepal_length, sepal_width, petal_length, petal_width],
	pred.prob_column = prob,
	pred.detail_column = detail,
	pred.encoding_column = encoding
USING SAMPLE_DATABASE.iris_xgb_model;
```

This prediction SQL follows https://github.com/sql-machine-learning/sqlflow/blob/develop/sql/python/test_magic_xgboost.py#L38

**Comment by BlackPoint-CX** [comment]
> Please refine the prediction SQL to
> 
> ```sql
> SELECT *
> FROM SAMPLE_DATABASE.iris_test
> PREDICT SAMPLE_DATABASE.iris_xgb_predict
> WITH
> 	pred.append_columns = [sepal_length, sepal_width, petal_length, petal_width],
> 	pred.prob_column = prob,
> 	pred.detail_column = detail,
> 	pred.encoding_column = encoding
> USING SAMPLE_DATABASE.iris_xgb_model;
> ```
> 
> This prediction SQL follows https://github.com/sql-machine-learning/sqlflow/blob/develop/sql/python/test_magic_xgboost.py#L38

It works for predict process and the predictions can be stored into relate Hive table.
However, when I try to select some samples from table in notebook , it still causes problem.

```
---------------------------------------------------------------------------
_Rendezvous                               Traceback (most recent call last)
~/miniconda/envs/sqlflow-dev/lib/python3.5/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/miniconda/envs/sqlflow-dev/lib/python3.5/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    398                         if cls is not object \
    399                                 and callable(cls.__dict__.get('__repr__')):
--> 400                             return _repr_pprint(obj, self, cycle)
    401 
    402             return _default_pprint(obj, self, cycle)

~/miniconda/envs/sqlflow-dev/lib/python3.5/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    693     """A pprint that just redirects to the normal repr function."""
    694     # Find newlines and replace them with p.break_()
--> 695     output = repr(obj)
    696     for idx,output_line in enumerate(output.splitlines()):
    697         if idx:

~/miniconda/envs/sqlflow-dev/lib/python3.5/site-packages/sqlflow/client.py in __repr__(self)
     57         from prettytable import PrettyTable
     58         table = PrettyTable(self._column_names)
---> 59         for row in self.rows():
     60             table.add_row(row)
     61         return table.__str__()

~/miniconda/envs/sqlflow-dev/lib/python3.5/site-packages/sqlflow/client.py in rows(self)
     44         if self._rows is None:
     45             self._rows = []
---> 46             for row in self._rows_gen():
     47                 self._rows.append(row)
     48                 yield row

~/miniconda/envs/sqlflow-dev/lib/python3.5/site-packages/sqlflow/client.py in rows_gen()
    144 
    145             def rows_gen():
--> 146                 for res in stream_response:
    147                     yield [cls._decode_any(a) for a in res.row.data]
    148             return Rows(column_names, rows_gen)

~/miniconda/envs/sqlflow-dev/lib/python3.5/site-packages/grpc/_channel.py in __next__(self)
    362 
    363     def __next__(self):
--> 364         return self._next()
    365 
    366     def next(self):

~/miniconda/envs/sqlflow-dev/lib/python3.5/site-packages/grpc/_channel.py in _next(self)
    356                         raise StopIteration()
    357                     elif self._state.code is not None:
--> 358                         raise self
    359 
    360     def __iter__(self):

_Rendezvous: <_Rendezvous of RPC that terminated with:
  status = StatusCode.UNKNOWN
  details = "sql: Scan error on column index 4, name "iris_xgb_predict.prob": converting driver.Value type float64 ("1.7999999523162842") to a int64: invalid syntax"
  debug_error_string = "{"created":"@1567078504.584789225","description":"Error received from peer ipv4:127.0.0.1:50051","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"sql: Scan error on column index 4, name "iris_xgb_predict.prob": converting driver.Value type float64 ("1.7999999523162842") to a int64: invalid syntax","grpc_status":2}"
>
```

But I can do this in Hive client.  
```
hive> select * from iris_xgb_predict limit 10 ;
OK
iris_xgb_predict.sepal_length	iris_xgb_predict.sepal_width	iris_xgb_predict.petal_length	iris_xgb_predict.petal_width	iris_xgb_predict.prob	iris_xgb_predict.detail	iris_xgb_predict.encoding	iris_xgb_predict.result
2.0	6.3	2.7	4.9	1.7999999523162842	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,6,2,2,6,2,2,6,2,2,6,2,2,6,2,6,6,2,6,6,2,4,6,2,2,5,2,2,2,2,2,2,2,2,4,2,2,2,0,2,2,0,2,2,0,2,2,0,2,2,0,2,2,0,2,2,0,2,2,0,2,2,0,2,2,0,4,2,0,2,2,0,4,2	NULL	NULL
```

**Comment by BlackPoint-CX** [comment]
It is more weird that the exception throws from other virtual env.
```
~/miniconda/envs/sqlflow-dev/lib/python3.5/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()
```
I am sure when running the code, the virtual env sqlflow-dev-py36 which is based on python 3.6 is active.
